version: "3.9"

services:
  app:
    image: ghcr.io/wolfres123/software-construction---team-4:latest
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    command: sh -c "cron && python -u server.py"
