name: Test Mobypark

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build test image
        run: |
          docker build -t mobypark:tests --target test ./MobyPark

      - name: Run API and tests in the same container
        run: |
          # Run container in interactive mode
          docker run --rm \
            -e BASE_URL=http://127.0.0.1:8001 \
            mobypark:tests \
            sh -c "
              # Start the API in the background
              python -u server.py &

              # Wait a few seconds for it to start
              sleep 5

              # Run pytest
              pytest tests
            "
