name: Test Mobypark

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build test image
        run: |
          docker build -t mobypark:tests --target test ./MobyPark

      - name: Run Integration tests
        run: |
          docker run --rm \
            -e BASE_URL=http://127.0.0.1:8000 \
            mobypark:tests \
            sh -c "
              python -u server.py &
              echo 'Waiting for server on 8000...'
              until curl -s http://127.0.0.1:8000 > /dev/null; do sleep 1; done
              pytest tests/Integration
            "


      - name: Run Systeem tests
        run: |
          docker run --rm \
            -e BASE_URL=http://127.0.0.1:8000 \
            mobypark:tests \
            sh -c "
              python -u server.py --port 8000 &
              echo 'Waiting for server on 8000...'
              until curl -s http://127.0.0.1:8000 > /dev/null; do sleep 1; done
              pytest tests/systeem_test
            "

